baseURL = 'https://gexin13.github.io/my-blog/'
languageCode = 'zh-CN'
title = "MoonStar's Blog"
theme = "hugo-theme-stack"
disqusShortname = "" # 如果使用 disqus 评论系统，在这里填写自己的 disqus 用户名 
hasCJKLanguage = true
enableEmoji = true

[permalinks]
    posts ="/:filename/"

[Menus] # 边栏目录
  main = [
      {Name = "Archives", URL = "<https://gexin13.github.io/my-blog/posts/>"},
      {Name = "Tags", URL = "<https://gexin13.github.io/my-blog/tags/>"},
      {Name = "Photos", URL = "<https://gexin13.github.io/my-blog/photos/>"}
  ]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."

[params.valine]
  enable = false
    appId = ''
    appKey = ''
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true

